language: java

jdk:
  - openjdk8
# Test & Build SpringBoot app
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo apt-get update
  - sudo apt-get install node
  # Docker Compose Install
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Download and install Docker libs
  - curl -L https://github.com/Ortus-Solutions/docker-buildfiles/archive/master.zip > docker.zip
  - unzip docker.zip -d workbench
  - mv workbench/docker-buildfiles-master workbench/docker

install:
  # Docker CFML Server Tests
  - bash ./set_up.sh

script:
  - mvn clean package
  - docker-compose build
  - docker-compose run test
# safelist
branches:
  only:
    - master
# set up cache
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: Ise82QmFoMwy7k3IIPRKCvq4bMkOtOIbMELCPujlyAfftFKI1Yk4oPZyZc+OhlG/H0FtdtfIiF+mMI87ImMEbIS8ldmME9D9VyPKaTPm5xYw3jVJK9syNjMKOGL6btL9YcMzDDNCU7YjNE6zqmFhKFOH5jHwdUnBuUeJ6psjoTbYJsm3XygP7J0ygUti60U4ym8uE+PfiHJU4vOgB50uTR69hiLVdPHP1NVU63lS6fSWqBeL819C/kGYxuMzO3vG3Ww5buM4w0cy6sq0QeYRie3pxl9RTUSkc+8CQKyP45QClbrzyrylEQcPhVvHNyKEkI0PFoLreqOsnIAHvOzROEU4wsl5gIoEeZdpMZVOFOC6q2n0GXExR5FJFX+7ck5EHXVCG9EXYrAL24/KrdyjvoyXAQ9settMaA/0HjtkrEZ2YifnSOpL81+GzCoWOkcx3rqb85ukIb+1CWxcVCVY3tHIxIPeMYpdQtDLZhCB1mbjZZgzBHfm+K8caTmEgNurhx4RcRiXm/HQcQbBiLVDS62G+amvHVIi0A6TpOV3Fw9yJEw2HNT/VI/gi64PhTTSEhAZa9JoAcNp2u2/j7hGiPQW9OWjO5mZGRJ+6pE64J+P/M49DLQoCg84qadPPwSZxctqryZ42bv30izEQ8nbBWsH+ccG2DDrfxFvANuuUAw=
  app: cvise
  script:
    - docker-compose up -d
  on:
    repo: CaribouW/leasing
sudo: true

