language: java
jdk:
  - openjdk8
# Test & Build SpringBoot app
before-install:
  - sudo apt-get update
  - sudo apt-get install docker.io
  - sudo apt-get install docker-compose
  - sudo apt-get install node
install: true
script:
  - bash ./set_up.sh
  - mvn clean package -Dmaven.test.skip=true 
# safelist
branches:
  only:
    - master
# set up cache
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: Ise82QmFoMwy7k3IIPRKCvq4bMkOtOIbMELCPujlyAfftFKI1Yk4oPZyZc+OhlG/H0FtdtfIiF+mMI87ImMEbIS8ldmME9D9VyPKaTPm5xYw3jVJK9syNjMKOGL6btL9YcMzDDNCU7YjNE6zqmFhKFOH5jHwdUnBuUeJ6psjoTbYJsm3XygP7J0ygUti60U4ym8uE+PfiHJU4vOgB50uTR69hiLVdPHP1NVU63lS6fSWqBeL819C/kGYxuMzO3vG3Ww5buM4w0cy6sq0QeYRie3pxl9RTUSkc+8CQKyP45QClbrzyrylEQcPhVvHNyKEkI0PFoLreqOsnIAHvOzROEU4wsl5gIoEeZdpMZVOFOC6q2n0GXExR5FJFX+7ck5EHXVCG9EXYrAL24/KrdyjvoyXAQ9settMaA/0HjtkrEZ2YifnSOpL81+GzCoWOkcx3rqb85ukIb+1CWxcVCVY3tHIxIPeMYpdQtDLZhCB1mbjZZgzBHfm+K8caTmEgNurhx4RcRiXm/HQcQbBiLVDS62G+amvHVIi0A6TpOV3Fw9yJEw2HNT/VI/gi64PhTTSEhAZa9JoAcNp2u2/j7hGiPQW9OWjO5mZGRJ+6pE64J+P/M49DLQoCg84qadPPwSZxctqryZ42bv30izEQ8nbBWsH+ccG2DDrfxFvANuuUAw=
  app: cvise
  on:
    repo: CaribouW/leasing  # 暂时先用个人的分支 , 之后将要改变为upstream的内容
sudo: true

