spring:
  data:
    mongodb:
#      uri: mongodb://my_user:password123@localhost:27017/my_database
      uri: mongodb://heroku_jzgcbjbx:4pjc5oe815md328o5vj49kmeqk@ds221435.mlab.com:21435/heroku_jzgcbjbx

