server:
  port: 8000
spring:
  data:
    mongodb:
      authentication-database: test
      username: my_user
      password: password123
      port: 8081
      host: 121.43.61.174
#      uri: mongodb://heroku_1cm1qpq0:8tpe6jf3nm507o22k6aq3hlu23@ds353457.mlab.com:53457/heroku_1cm1qpq0
